services:
  db:
    image: "postgres:17"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: "${DB_USER?:DB_USER not set}"
      POSTGRES_PASSWORD: "${DB_PWD?:DB_PWD not set}"
      POSTGRES_DB: "polls"
    volumes:
      - ./db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1gb
  app:
    build:
      context: .
      args:
        SECRET_KEY: "${SECRET_KEY?:SECRET_KEY not set}"
    image: ku-polls
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    environment:
      SECRET_KEY: "${SECRET_KEY?:SECRET_KEY not set}"
      DATABASE_USERNAME: "${DB_USER?:DB_USER not set}"
      DATABASE_PASSWORD: "${DB_PWD?:DB_PWD not set}"
      DATABASE_HOST: db
      DATABASE_PORT: "${DB_PORT?:DB_PORT not set}"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    deploy:
      resources:
        limits:
          memory: 256mb