name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Django environment
      run: |
        export DJANGO_SETTINGS_MODULE=mysite.settings
        python manage.py test polls